export const QUERY_DATA_LIMIT = 10;

export const MODAL_QUERY_DATA_LIMIT = 5;

export const DETAILED_GENERAL_LEDGER_LIMIT = 2;

export const REPORT_DATE_FORMAT = "DD MMM YYYY";

export const SYSTEM_ACCOUNT_CODE_INVENTORY_ASSET = "106";
export const SYSTEM_ACCOUNT_CODE_SALES = "401";
export const SYSTEM_ACCOUNT_CODE_COGS = "506";
